### ISSUE TITLE
body attributes not rendered

### ISSUE THREAD

**Issue by Cl3MM** [marcstark/meteor-angular-jade-extended#1]
I've created an app.jade file, and attributes don't seem to be picked up by the body tag:

```
body(class="test", ng-app="myApp")
```

just renders

```
<body></body>
```

Am I doing something wrong ?

Thanks for your work !

**Comment by marcoschaule** [comment]
Of course not! It is just a use case I didn't consider. Let's see how to implement that.

Since Meteor without Angular and Jade complains if you use `class="<something>"` in more than one `body`-tags in your app, the question is: should I try to stick with that behaviour or should I try to "collect" all classes from all bodies. If so, what about tags like `ng-app`? In that case, only the last one could be considered, and would override all previous uses of it.

What do you think?

**Comment by Cl3MM** [comment]
I agree with your solutions: 
- You should let meteor handle errors its own way like it currently does.
- There should only be one `ng-app` attribute in the body tag. I would throw a warning if more than one is found.

**Comment by marcoschaule** [comment]
So. done. All `class` attributes are now merged, other attributes are just added to main layout's `body` tag. Already existing attributes are replaces by new ones, depending on Meteor's file load order.

**Comment by Cl3MM** [comment]
Thanks, works like a charm !
Great plugin by the way ! Very well documented ;)
